# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a9e542feecc232ce4f04a09797bedaf31fd1f82d04ed2062e29f907ab272250ebdd57ab5656a58be12c85a8f26b13d935df5848325d3501de8fa2ed00f5def6

test:
  secret_key_base: 8e1a19d9cf61b07adf46923b1b2b70f8a50dbd9b8bb9115e026ea8a45552a9ab4f5c5bf90eb0592bd11829fafee81841383ab30f55d1518a58e04511e05d5f89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
